informalsystems/hermes-sdk

crates/cli/cli/src/commands/mod.rs
crates/cli/cli/src/commands/query/connections.rs
crates/cli/cli/src/commands/query/mod.rs

Closes: #129
This PR adds the CLI `query connections` which queries all connections for a given chain.
There are also two optional flags, one to specify a counterparty chain to filter the connection and a one to output more information about connections.
______

Add CLI to query all connections of a chain

---

Cargo.lock
crates/cli/cli-framework/Cargo.toml
crates/cli/cli-framework/src/application/boot.rs
crates/cli/cli-framework/src/application/log.rs
crates/cli/cli-framework/src/application/mod.rs
crates/cli/cli-framework/src/command.rs
crates/cli/cli-framework/src/lib.rs
crates/cli/cli-framework/src/output.rs
crates/cli/cli/Cargo.toml
crates/cli/cli/bin/hermes.rs
crates/cli/cli/src/application/mod.rs
crates/cli/cli/src/commands/channel/create.rs
crates/cli/cli/src/commands/channel/mod.rs
crates/cli/cli/src/commands/client/create.rs
crates/cli/cli/src/commands/client/mod.rs
crates/cli/cli/src/commands/connection/create.rs
crates/cli/cli/src/commands/connection/mod.rs
crates/cli/cli/src/commands/mod.rs
crates/cli/cli/src/commands/query/client/mod.rs
crates/cli/cli/src/commands/query/client/state.rs
crates/cli/cli/src/commands/query/mod.rs
crates/cli/cli/src/commands/start.rs

Closes: #131
Closes: #133
This PR also ports the `Output` type from Hermes and adds support for JSON output.
______

Implement `query client state` command

---

crates/cli/cli/src/commands/query/connections.rs

Cleanup and harmonize output of `query connections` command

---

crates/cli/cli/Cargo.toml
crates/cli/cli/src/commands/query/channel/client.rs
crates/cli/cli/src/commands/query/channel/end.rs
crates/cli/cli/src/commands/query/channel/ends.rs
crates/cli/cli/src/commands/query/channel/mod.rs
crates/cli/cli/src/commands/query/mod.rs

Implement `query channel` subcommands

---

Cargo.lock
crates/sovereign/sovereign-client-components/src/cosmos/impls/client/create_client_message.rs
crates/sovereign/sovereign-client-components/src/sovereign/context/mod.rs
crates/sovereign/sovereign-client-components/src/sovereign/context/sovereign_counterparty.rs
crates/sovereign/sovereign-client-components/src/sovereign/impls/types/client_state.rs
crates/sovereign/sovereign-client-components/src/sovereign/impls/types/mod.rs
crates/sovereign/sovereign-client-components/src/sovereign/mod.rs
crates/sovereign/sovereign-integration-tests/Cargo.toml
crates/sovereign/sovereign-integration-tests/tests/create_client.rs
crates/wasm/wasm-client-components/Cargo.toml
crates/wasm/wasm-client-components/src/impls/decoders/client_state.rs

Closes: #194
Add the implementation to query a Sovereign client state
______

Add query for Sovereign client state

---

Cargo.lock
crates/sovereign/sovereign-client-components/src/sovereign/traits/data_chain/mod.rs
crates/sovereign/sovereign-cosmos-relayer/src/contexts/sovereign_chain.rs
crates/sovereign/sovereign-integration-tests/Cargo.toml
crates/sovereign/sovereign-integration-tests/tests/create_client.rs

Closes: #195
This PR adds a trait `DataChain` which is used to specify the type of DataChain and implement a getter method to retrieve a reference to its DA chain.
This PR also adds a DA chain to the SovereignChain as a `CosmosChain` since the implementation of the Celestia chain used as DA chain is very similar to a Cosmos chain.
______

Add `DataChain` trait and implement it for `SovereignChain`

---

Cargo.lock
Cargo.toml
crates/cosmos/cosmos-chain-components/src/impls/queries/client_state.rs
crates/sovereign/sovereign-chain-components/src/sovereign/impls/sovereign_to_cosmos/client/update_client_payload.rs
crates/sovereign/sovereign-integration-tests/tests/cosmos_to_sovereign.rs
crates/sovereign/sovereign-integration-tests/tests/create_client.rs
crates/sovereign/sovereign-relayer/src/contexts/logger.rs
crates/sovereign/sovereign-relayer/src/contexts/sovereign_rollup.rs
crates/sovereign/sovereign-rollup-components/Cargo.toml
crates/sovereign/sovereign-rollup-components/src/components.rs
crates/sovereign/sovereign-rollup-components/src/impls/mod.rs
crates/sovereign/sovereign-rollup-components/src/impls/queries/client_state.rs
crates/sovereign/sovereign-rollup-components/src/impls/queries/mod.rs
crates/sovereign/sovereign-rollup-components/src/types/height.rs

Implement client state querier for Sovereign rollup

---

crates/relayer/relayer-components/src/chain/impls/forward/mod.rs
crates/relayer/relayer-components/src/chain/impls/forward/queries/chain_status.rs
crates/relayer/relayer-components/src/chain/impls/forward/queries/client_state.rs
crates/relayer/relayer-components/src/chain/impls/forward/queries/mod.rs
crates/relayer/relayer-components/src/chain/impls/mod.rs
crates/sovereign/sovereign-chain-components/src/sovereign/components.rs
crates/sovereign/sovereign-chain-components/src/sovereign/impls/types/chain.rs
crates/sovereign/sovereign-relayer/src/contexts/sovereign_chain.rs
crates/sovereign/sovereign-relayer/src/contexts/sovereign_rollup.rs
crates/sovereign/sovereign-relayer/src/exts/cosmos/chain.rs
crates/sovereign/sovereign-rollup-components/src/components.rs
crates/sovereign/sovereign-rollup-components/src/impls/queries/chain_status.rs
crates/sovereign/sovereign-rollup-components/src/impls/queries/client_state.rs
crates/sovereign/sovereign-rollup-components/src/impls/queries/mod.rs

Implement chain status querier for Sovereign rollup

---

crates/cosmos/cosmos-chain-components/src/components/client.rs
crates/cosmos/cosmos-chain-components/src/impls/queries/consensus_state_height.rs
crates/cosmos/cosmos-relayer/src/impls/error.rs
crates/relayer/relayer-components/src/chain/impls/forward/queries/consensus_state_height.rs
crates/relayer/relayer-components/src/chain/impls/forward/queries/mod.rs
crates/relayer/relayer-components/src/chain/impls/queries/consensus_state_height.rs
crates/relayer/relayer-components/src/chain/impls/queries/mod.rs
crates/sovereign/sovereign-chain-components/src/sovereign/components.rs
crates/sovereign/sovereign-integration-tests/tests/cosmos_to_sovereign.rs
crates/sovereign/sovereign-relayer/src/contexts/sovereign_chain.rs
crates/sovereign/sovereign-relayer/src/contexts/sovereign_rollup.rs
crates/sovereign/sovereign-rollup-components/src/components.rs
crates/sovereign/sovereign-rollup-components/src/impls/queries/consensus_state_height.rs
crates/sovereign/sovereign-rollup-components/src/impls/queries/mod.rs

Implement `ConsensusStateHeightQuerier` for Sovereign rollup

---

crates/relayer/relayer-components/src/chain/impls/forward/message_builders/connection_handshake.rs
crates/relayer/relayer-components/src/chain/impls/forward/message_builders/mod.rs
crates/relayer/relayer-components/src/chain/impls/forward/mod.rs
crates/sovereign/sovereign-chain-components/src/sovereign/components.rs
crates/sovereign/sovereign-chain-components/src/sovereign/impls/types/payload.rs
crates/sovereign/sovereign-chain-components/src/sovereign/types/payloads/connection.rs
crates/sovereign/sovereign-relayer/src/contexts/sovereign_chain.rs
crates/sovereign/sovereign-relayer/src/contexts/sovereign_rollup.rs
crates/sovereign/sovereign-relayer/src/lib.rs
crates/sovereign/sovereign-rollup-components/src/components.rs

Implement wiring for connection handshake components for `SovereignChain`

---

crates/cosmos/cosmos-chain-components/src/components/client.rs
crates/cosmos/cosmos-chain-components/src/components/cosmos_to_cosmos.rs
crates/relayer/relayer-components/src/chain/impls/delegate/message_builders/channel_handshake.rs
crates/relayer/relayer-components/src/chain/impls/delegate/message_builders/mod.rs
crates/relayer/relayer-components/src/chain/impls/forward/message_builders/channel_handshake.rs
crates/relayer/relayer-components/src/chain/impls/forward/message_builders/mod.rs
crates/sovereign/sovereign-chain-components/src/cosmos/components.rs
crates/sovereign/sovereign-chain-components/src/cosmos/impls/sovereign_to_cosmos/channel_handshake_message.rs
crates/sovereign/sovereign-chain-components/src/sovereign/components.rs
crates/sovereign/sovereign-chain-components/src/sovereign/impls/sovereign_to_cosmos/channel/channel_handshake_payload.rs
crates/sovereign/sovereign-chain-components/src/sovereign/impls/sovereign_to_cosmos/channel/mod.rs
crates/sovereign/sovereign-chain-components/src/sovereign/impls/sovereign_to_cosmos/mod.rs
crates/sovereign/sovereign-integration-tests/tests/sovereign_to_cosmos.rs
crates/sovereign/sovereign-relayer/src/contexts/sovereign_chain.rs
crates/sovereign/sovereign-relayer/src/exts/cosmos/chain.rs

Closes: #256
This PR implements:
* `build_channel_open_init_message` for a `CosmosMessage`
* Wires the components required for the channel handshake from Sovereign to Cosmos
______

Sovereign to Cosmos Channel Open Init

---

crates/sovereign/sovereign-chain-components/src/cosmos/impls/sovereign_to_cosmos/channel_handshake_message.rs
crates/sovereign/sovereign-chain-components/src/sovereign/impls/sovereign_to_cosmos/channel/channel_handshake_payload.rs
crates/sovereign/sovereign-chain-components/src/sovereign/types/payloads/channel.rs
crates/sovereign/sovereign-integration-tests/tests/sovereign_to_cosmos.rs

Closes: #259
This PR implements:
* `build_channel_open_ack_payload` for `SovereignChannelOpenAckPayload`
* `build_channel_open_ack_message` for `CosmosMessage`
______

Sovereign to Cosmos Channel Open Ack

---

crates/relayer/relayer-components/src/chain/impls/forward/queries/client_state.rs
crates/sovereign/sovereign-chain-components/src/cosmos/components.rs
crates/sovereign/sovereign-chain-components/src/sovereign/components.rs
crates/sovereign/sovereign-chain-components/src/sovereign/impls/types/chain.rs
crates/sovereign/sovereign-integration-tests/tests/cosmos_to_sovereign.rs
crates/sovereign/sovereign-relayer/src/contexts/sovereign_chain.rs
crates/sovereign/sovereign-relayer/src/contexts/sovereign_rollup.rs
crates/sovereign/sovereign-relayer/src/exts/cosmos/chain.rs
crates/sovereign/sovereign-rollup-components/src/components.rs
crates/sovereign/sovereign-rollup-components/src/impls/queries/client_state.rs

Implement `CanQueryClientStateWithProofs` for Sovereign rollup

---

crates/relayer/relayer-components/src/chain/impls/forward/queries/consensus_state.rs
crates/sovereign/sovereign-chain-components/src/cosmos/components.rs
crates/sovereign/sovereign-chain-components/src/sovereign/components.rs
crates/sovereign/sovereign-integration-tests/tests/cosmos_to_sovereign.rs
crates/sovereign/sovereign-relayer/src/contexts/sovereign_chain.rs
crates/sovereign/sovereign-relayer/src/contexts/sovereign_rollup.rs
crates/sovereign/sovereign-relayer/src/exts/cosmos/chain.rs
crates/sovereign/sovereign-rollup-components/src/components.rs
crates/sovereign/sovereign-rollup-components/src/impls/queries/consensus_state.rs
crates/sovereign/sovereign-rollup-components/src/lib.rs

Implement `CanQueryConsensusStateWithProofs` for Sovereign rollup

---

crates/cosmos/cosmos-chain-components/src/components/client.rs
crates/cosmos/cosmos-chain-components/src/impls/events.rs
crates/cosmos/cosmos-chain-components/src/methods/event.rs
crates/cosmos/cosmos-relayer/src/chain/components.rs
crates/cosmos/cosmos-relayer/src/chain/impls/events.rs
crates/relayer/relayer-components/src/chain/impls/forward/queries/channel_end.rs
crates/relayer/relayer-components/src/chain/impls/forward/queries/mod.rs
crates/relayer/relayer-components/src/chain/traits/types/ibc_events/channel.rs
crates/sovereign/sovereign-chain-components/src/sovereign/components.rs
crates/sovereign/sovereign-relayer/src/contexts/cosmos_to_sovereign_relay.rs
crates/sovereign/sovereign-relayer/src/contexts/sovereign_chain.rs
crates/sovereign/sovereign-relayer/src/contexts/sovereign_rollup.rs
crates/sovereign/sovereign-relayer/src/contexts/sovereign_to_cosmos_relay.rs
crates/sovereign/sovereign-relayer/src/exts/cosmos/chain.rs
crates/sovereign/sovereign-rollup-components/src/components.rs
crates/sovereign/sovereign-rollup-components/src/impls/events.rs

Implement channel handshake between Sovereign and Cosmos

---

crates/cosmos/cosmos-chain-components/src/components/client.rs
crates/cosmos/cosmos-chain-components/src/impls/queries/mod.rs
crates/cosmos/cosmos-chain-components/src/impls/queries/packet_acknowledgement.rs
crates/cosmos/cosmos-chain-components/src/impls/queries/packet_acknowledgements.rs
crates/cosmos/cosmos-relayer/src/chain/checks.rs
crates/cosmos/cosmos-relayer/src/chain/components.rs
crates/relayer/relayer-components/src/chain/impls/forward/queries/mod.rs
crates/relayer/relayer-components/src/chain/impls/forward/queries/packet_acknowledgement.rs
crates/sovereign/sovereign-chain-components/src/sovereign/components.rs
crates/sovereign/sovereign-chain-components/src/sovereign/impls/types/chain.rs
crates/sovereign/sovereign-relayer/src/contexts/sovereign_chain.rs
crates/sovereign/sovereign-relayer/src/contexts/sovereign_rollup.rs
crates/sovereign/sovereign-rollup-components/src/components.rs
crates/sovereign/sovereign-rollup-components/src/impls/queries/mod.rs
crates/sovereign/sovereign-rollup-components/src/impls/queries/packet_acknowledgement.rs
crates/sovereign/sovereign-rollup-components/src/impls/types/rollup.rs

Implement packet acknowledgement querier

---

crates/cosmos/cosmos-chain-components/src/components/client.rs
crates/cosmos/cosmos-chain-components/src/impls/queries/mod.rs
crates/cosmos/cosmos-chain-components/src/impls/queries/packet_receipt.rs
crates/cosmos/cosmos-chain-components/src/impls/types/chain.rs
crates/cosmos/cosmos-relayer/src/chain/checks.rs
crates/cosmos/cosmos-relayer/src/chain/components.rs
crates/relayer/relayer-components/src/chain/impls/forward/queries/mod.rs
crates/relayer/relayer-components/src/chain/impls/forward/queries/packet_receipt.rs
crates/relayer/relayer-components/src/chain/impls/types/mod.rs
crates/relayer/relayer-components/src/chain/impls/types/receipt.rs
crates/relayer/relayer-components/src/chain/traits/queries/packet_receipt.rs
crates/sovereign/sovereign-chain-components/src/sovereign/components.rs
crates/sovereign/sovereign-chain-components/src/sovereign/impls/types/chain.rs
crates/sovereign/sovereign-relayer/src/contexts/sovereign_chain.rs
crates/sovereign/sovereign-relayer/src/contexts/sovereign_rollup.rs
crates/sovereign/sovereign-rollup-components/src/components.rs
crates/sovereign/sovereign-rollup-components/src/impls/queries/mod.rs
crates/sovereign/sovereign-rollup-components/src/impls/queries/packet_receipt.rs
crates/sovereign/sovereign-rollup-components/src/impls/types/rollup.rs

Implement packet receipt querier

---

Cargo.lock
Cargo.toml
crates/cosmos/cosmos-chain-components/src/impls/client/create_client_payload.rs
crates/cosmos/cosmos-chain-components/src/impls/events.rs
crates/cosmos/cosmos-chain-components/src/impls/transaction/event.rs
crates/cosmos/cosmos-relayer/src/contexts/chain.rs
crates/mock/mock-cosmos-relayer/src/contexts/basecoin.rs
crates/mock/mock-cosmos-relayer/src/contexts/builder.rs
crates/mock/mock-cosmos-relayer/src/tests/init.rs
crates/sovereign/sovereign-chain-components/src/sovereign/impls/sovereign_to_cosmos/client/create_client_payload.rs
crates/sovereign/sovereign-integration-tests/tests/cosmos_to_sovereign.rs
crates/sovereign/sovereign-rollup-components/src/impls/transaction/encode_tx.rs
crates/sovereign/sovereign-rollup-components/src/impls/transaction/query_nonce.rs

Update dependencies from `hermes`, `ibc-rs`, `sovereign-ibc`, ibc-proto`, etc.
Also closes: #333.

Update IBC dependencies

---

Cargo.lock
Cargo.toml
crates/cosmos/cosmos-chain-components/src/impls/client/create_client_message.rs
crates/cosmos/cosmos-integration-tests/src/contexts/chain_driver.rs
crates/cosmos/cosmos-integration-tests/src/impls/bootstrap/build_cosmos_chain_driver.rs
crates/cosmos/cosmos-relayer/src/impls/error.rs
crates/relayer/relayer-components-extra/src/components/extra/build.rs
crates/relayer/relayer-components/src/build/impls/bootstrap/birelay.rs
crates/relayer/relayer-components/src/chain/impls/queries/query_and_convert_client_state.rs
crates/relayer/relayer-components/src/chain/impls/queries/query_and_convert_consensus_state.rs
crates/relayer/relayer-components/src/components/default/build.rs
crates/relayer/relayer-components/src/multi/traits/birelay_at.rs
crates/relayer/relayer-components/src/multi/traits/relay_at.rs
crates/relayer/relayer-components/src/relay/impls/fields.rs
crates/relayer/relayer-components/src/relay/traits/chains.rs
crates/runtime/async-runtime-components/src/channel/traits.rs
crates/runtime/async-runtime-components/src/stream/traits/boxed.rs
crates/runtime/runtime-components/src/traits/os/reserve_port.rs
crates/runtime/tokio-runtime-components/src/components/parallel.rs
crates/runtime/tokio-runtime-components/src/impls/os/reserve_port.rs
crates/runtime/tokio-runtime-components/src/traits/channel.rs
crates/test/test-components/src/chain_driver/traits/config.rs
crates/test/test-components/src/relay_driver/run.rs
crates/test/test-components/src/setup/impls/run_test.rs
crates/test/test-components/src/setup/traits/run_test.rs

Tracks changes in https://github.com/informalsystems/cgp/pull/20

Remove Async bounds in component traits and macros

---

crates/runtime/runtime/src/impls/runtime/error.rs
crates/runtime/runtime/src/types/error.rs
crates/runtime/tokio-runtime-components/src/impls/os/exec_command.rs

Improves error handling over #446.

Add CommandNotFound error type for better exec command failure diagnostic

---

Cargo.lock
Cargo.toml
crates/cosmos/cosmos-chain-components/src/impls/queries/packet_commitments.rs
crates/solomachine/solomachine-chain-components/Cargo.toml
crates/solomachine/solomachine-relayer/Cargo.toml

Update the Hermes v1 dependencies to use the git repository.
______

Patch Hermes v1 dependency to latest

---

crates/cli/cli-components/src/impls/commands/client/mod.rs
crates/cli/cli-components/src/impls/commands/client/update.rs
crates/cli/cli/src/contexts/app.rs

Closes: #XXX
This PR adds a generic `client update` CLI
______

Generic client update CLI implementation

---

crates/cli/cli-components/src/impls/commands/queries/chain.rs
crates/cli/cli-components/src/impls/commands/queries/chain_status.rs
crates/cli/cli-components/src/impls/commands/queries/mod.rs
crates/cli/cli/src/commands/query/mod.rs
crates/cli/cli/src/contexts/app.rs
crates/cosmos/cosmos-chain-components/src/types/status.rs

Closes: #XXX
This PR adds the `query chain` subcommand and the generic `query chain status` CLI.
______

Add `query chain` subcommand and `query chain status` CLI

---

crates/cli/cli-components/src/impls/commands/queries/balance.rs
crates/cli/cli-components/src/impls/commands/queries/mod.rs
crates/cli/cli-components/src/impls/commands/queries/wallet.rs
crates/cli/cli/src/commands/query/mod.rs
crates/cli/cli/src/contexts/app.rs
crates/cosmos/cosmos-test-components/src/chain/types/amount.rs
crates/cosmos/cosmos-test-components/src/chain/types/denom.rs

Closes: #XXX
This PR adds the `query wallet` subcommand and `query wallet balance` CLI
______

Add `query wallet` subcommand and `query wallet balance` CLI

---

.github/workflows/integration-tests.yaml
crates/cli/cli-components/src/impls/commands/start.rs
crates/cosmos/cosmos-integration-tests/src/contexts/binary_channel/setup.rs
crates/cosmos/cosmos-integration-tests/src/contexts/binary_channel/test_driver.rs
crates/cosmos/cosmos-relayer/src/contexts/birelay.rs
crates/cosmos/cosmos-relayer/src/contexts/build.rs
crates/relayer/relayer-components/src/build/traits/builders/birelay_builder.rs
crates/relayer/relayer-components/src/multi/traits/birelay_at.rs

Related: https://github.com/informalsystems/ibc-starknet/pull/245

Minor refactoring for BiRelay components

---

Cargo.lock

Updating crate dependencies to remove some PRs opened by Dependabot.

Update crate dependencies

---

crates/logging/logging-components/src/traits/logger.rs
docs/notes/README.md
docs/notes/logging.md

[Rendered](https://github.com/informalsystems/hermes-sdk/blob/soares/docs-4/docs/notes/logging.md)

Add documentation for logging

---

crates/cli/cli-components/src/traits/parse.rs
docs/notes/README.md
docs/notes/cli.md

[Rendered](https://github.com/informalsystems/hermes-sdk/blob/soares/docs-5/docs/notes/cli.md)

Add documentation for CLI

---

crates/cosmos/cosmos-integration-tests/src/contexts/binary_channel/test_driver.rs
crates/cosmos/cosmos-integration-tests/src/contexts/chain_driver.rs
crates/cosmos/cosmos-integration-tests/tests/cosmos_integration_tests.rs
crates/cosmos/cosmos-test-components/src/chain/impls/upgrade_client.rs
crates/test/test-components/src/test_case/traits/upgrade_client.rs
crates/test/test-suite/src/tests/upgrade_client.rs

Closes: #XXX
This PR migrates the Client Upgrade test components from the `TestDriver` to the `ChainDriver` allowing implementation per chain instead of per test driver.
______

Migrate client upgrade test components from TestDriver to ChainDriver
