crates/relayer-all-in-one/src/all_for_one/birelay.rs
crates/relayer-all-in-one/src/all_for_one/relay.rs
crates/relayer-components-extra/src/components/extra/birelay.rs
crates/relayer-components-extra/src/components/extra/closures/relay/auto_relayer.rs
crates/relayer-components-extra/src/components/extra/relay.rs
crates/relayer-components-extra/src/relay/components/auto_relayers/parallel_bidirectional.rs
crates/relayer-components-extra/src/relay/components/auto_relayers/parallel_event.rs
crates/relayer-components-extra/src/relay/components/auto_relayers/parallel_two_way.rs
crates/relayer-components/src/components/default/birelay.rs
crates/relayer-components/src/components/default/closures/relay/auto_relayer.rs
crates/relayer-components/src/components/default/relay.rs
crates/relayer-components/src/core/mod.rs
crates/relayer-components/src/core/traits/mod.rs
crates/relayer-components/src/core/traits/run.rs
crates/relayer-components/src/lib.rs
crates/relayer-components/src/relay/components/auto_relayers/concurrent_bidirectional.rs
crates/relayer-components/src/relay/components/auto_relayers/concurrent_event.rs
crates/relayer-components/src/relay/components/auto_relayers/concurrent_two_way.rs
crates/relayer-components/src/relay/components/auto_relayers/sequential_event.rs
crates/relayer-components/src/relay/traits/components/auto_relayer.rs
tools/integration-test/src/tests/transfer.rs
tools/test-framework/src/framework/binary/next.rs

- The `CanAutoRelay` and `AutoRelayer` traits have been renamed to `CanRun` and `Runner` so that they can be used in any context.
- The `CanAutoRelayWithTarget` and `AutoRelayerWithTarget` traits have been renamed to `CanAutoRelay` and `AutoRelayer`.

Replace AutoRelayer component with a generalized Runner component

---

Cargo.lock
crates/cosmos/cosmos-integration-tests/Cargo.toml
crates/cosmos/cosmos-integration-tests/src/contexts/bootstrap.rs
crates/cosmos/cosmos-integration-tests/src/contexts/chain.rs
crates/cosmos/cosmos-integration-tests/src/tests/bootstrap.rs
crates/cosmos/cosmos-relayer/src/contexts/builder.rs
crates/cosmos/cosmos-test-components/src/bootstrap/components/cosmos_sdk.rs
crates/cosmos/cosmos-test-components/src/bootstrap/components/cosmos_sdk_legacy.rs
crates/cosmos/cosmos-test-components/src/bootstrap/impls/chain/bootstrap_chain.rs
crates/cosmos/cosmos-test-components/src/bootstrap/impls/chain/start_chain.rs
crates/cosmos/cosmos-test-components/src/bootstrap/traits/chain/start_chain.rs
tools/integration-test/src/tests/context.rs

This PR adds the step to construct the `CosmosChain` context inside the bootstrap context after bootstrapping a chain full node.

Build `CosmosChain` inside test bootstrap

---

crates/cli/cli/src/commands/query/client/mod.rs
crates/cli/cli/src/commands/query/client/state.rs
crates/cli/cli/src/commands/query/client/status.rs
crates/cosmos/cosmos-client-components/src/impls/types/chain.rs
crates/cosmos/cosmos-relayer/src/chain/impls/fields.rs
crates/mock/mock-cosmos-relayer/src/impls/chain.rs
crates/mock/mock-relayer/src/relayer_mock/base/impls/chain.rs
crates/mock/mock-relayer/src/relayer_mock/base/types/aliases.rs
crates/relayer/relayer-components/src/chain/traits/queries/client_status.rs
crates/relayer/relayer-components/src/chain/traits/queries/mod.rs
crates/relayer/relayer-components/src/chain/traits/types/client_state.rs
crates/relayer/relayer-components/src/chain/traits/types/consensus_state.rs
crates/relayer/relayer-components/src/chain/traits/types/timestamp.rs
crates/relayer/relayer-components/src/relay/types/relay_to_chain.rs

Closes: #155 
```
❯ cargo run -p hermes-cli -- query client status --chain ibc0 --client 07-tendermint-1
2024-02-13T11:58:35.236844Z  INFO Client `07-tendermint-1` is active
2024-02-13T11:58:35.236990Z  INFO Active
```
```
❯ cargo run -p hermes-cli -- --json query client status --chain ibc0 --client 07-tendermint-1
{"timestamp":"2024-02-13T11:58:02.701839Z","level":"INFO","fields":{"message":"Client `07-tendermint-1` is active"}}
{"result":"active","status":"success"}
```
______

Add `query client status` CLI for Cosmos chains

---

.github/workflows/integration-tests-next.yaml
crates/sovereign/sovereign-test-components/src/bootstrap/impls/generate_rollup_genesis.rs
crates/sovereign/sovereign-test-components/src/bootstrap/impls/init_rollup_node_config.rs
crates/sovereign/sovereign-test-components/src/types/rollup_genesis_config.rs
crates/sovereign/sovereign-test-components/src/types/rollup_node_config.rs
flake.lock

Update to new rollup Nix build from https://github.com/informalsystems/sov-rollup-starter/pull/2.

Update sov-rollup-starter Nix dependency

---

Cargo.lock
Cargo.toml
crates/runtime/tokio-runtime-components/Cargo.toml
crates/sovereign/sovereign-client-components/src/sovereign/types/message.rs
crates/sovereign/sovereign-client-components/src/sovereign/types/messages/ibc.rs
crates/sovereign/sovereign-client-components/src/sovereign/types/messages/mod.rs
crates/sovereign/sovereign-integration-tests/Cargo.toml
crates/sovereign/sovereign-integration-tests/tests/bootstrap.rs
crates/sovereign/sovereign-integration-tests/tests/cosmos_to_sovereign.rs
crates/sovereign/sovereign-integration-tests/tests/create_client.rs
crates/sovereign/sovereign-integration-tests/tests/ibc.rs
crates/sovereign/sovereign-test-components/Cargo.toml
flake.lock

The sovereign integration tests are now using a new version of sov-rollup-starter that includes sovereign-ibc. The test for sending CreateClient message to sovereign-ibc is currently partially working. However publishing a create client message currently fails, because ibc-rs expects the absence of frozen height to be encoded as `None`, but `ibc-relayer-types` encode it as a zero height here: https://github.com/informalsystems/hermes/blob/master/crates/relayer-types/src/clients/ics07_tendermint/client_state.rs#L308-L313
A fix for the test will be done in a separate PR, with proper refactoring on how to handle decoding and encoding of protobuf.

Update sovereign-rollup-starter to version that includes IBC

---

Cargo.lock
crates/sovereign/sovereign-client-components/src/cosmos/impls/connection_handshake_message.rs
crates/sovereign/sovereign-client-components/src/sovereign/components/chain.rs
crates/sovereign/sovereign-client-components/src/sovereign/impls/connection/connection_handshake_payload.rs
crates/sovereign/sovereign-client-components/src/sovereign/types/payloads/connection.rs
crates/sovereign/sovereign-cosmos-relayer/src/contexts/sovereign_chain.rs
crates/sovereign/sovereign-integration-tests/Cargo.toml
crates/sovereign/sovereign-integration-tests/tests/create_client.rs

Closes: #212
This PR builds the `SovereignConnectionOpenInitPayload` and the `build_connection_open_init_message` method to build a `CosmosMessage`.
______

Connection Init between Sovereign and Cosmos on Cosmos side

---

Cargo.lock
crates/cosmos/cosmos-chain-components/src/components/client.rs
crates/cosmos/cosmos-chain-components/src/impls/events.rs
crates/cosmos/cosmos-chain-components/src/impls/mod.rs
crates/cosmos/cosmos-chain-components/src/methods/event.rs
crates/cosmos/cosmos-relayer/src/chain/components.rs
crates/cosmos/cosmos-relayer/src/chain/impls/events.rs
crates/mock/mock-cosmos-relayer/src/impls/chain.rs
crates/relayer/relayer-components/src/chain/traits/types/create_client.rs
crates/relayer/relayer-components/src/relay/impls/create_client.rs
crates/solomachine/solomachine-relayer/src/impls/chain/types.rs
crates/sovereign/sovereign-chain-components/src/sovereign/components.rs
crates/sovereign/sovereign-chain-components/src/sovereign/components/chain.rs
crates/sovereign/sovereign-chain-components/src/sovereign/components/mod.rs
crates/sovereign/sovereign-chain-components/src/sovereign/impls/types/chain.rs
crates/sovereign/sovereign-chain-components/src/sovereign/impls/types/mod.rs
crates/sovereign/sovereign-integration-tests/src/impls/build_rollup_driver.rs
crates/sovereign/sovereign-integration-tests/tests/cosmos_to_sovereign.rs
crates/sovereign/sovereign-integration-tests/tests/create_client.rs
crates/sovereign/sovereign-relayer/Cargo.toml
crates/sovereign/sovereign-relayer/src/contexts/cosmos_to_sovereign_relay.rs
crates/sovereign/sovereign-relayer/src/contexts/sovereign_chain.rs
crates/sovereign/sovereign-relayer/src/contexts/sovereign_rollup.rs
crates/sovereign/sovereign-relayer/src/contexts/sovereign_to_cosmos_relay.rs
crates/sovereign/sovereign-rollup-components/src/components.rs
crates/sovereign/sovereign-rollup-components/src/impls/events.rs
crates/sovereign/sovereign-rollup-components/src/impls/mod.rs
crates/sovereign/sovereign-rollup-components/src/impls/types/mod.rs
crates/sovereign/sovereign-rollup-components/src/impls/types/rollup.rs
crates/sovereign/sovereign-rollup-components/src/lib.rs

- The relay contexts `CosmosToSovereignRelay` and `SovereignToCosmosRelay` now implement `CanCreateClient` for both source and destination targets.
- The `cosmos_to_sovereign` test is updated to use the relay contexts to create a Cosmos client on Sovereign.

Implement `CanCreateClient` for Sovereign relay contexts

---

crates/sovereign/sovereign-rollup-components/src/impls/cosmos_to_sovereign/client/create_client_message.rs
crates/sovereign/sovereign-rollup-components/src/impls/cosmos_to_sovereign/client/update_client_message.rs
crates/sovereign/sovereign-rollup-components/src/types/message.rs
crates/sovereign/sovereign-rollup-components/src/types/messages/ibc.rs

The previous refactoring caused IBC messages that are embedded inside `SovereignMessage` to return `None` when retrieving the counterparty proof height. This causes the UpdateClient message to not be built by the relayer when submitting the IBC messages.

Add counterparty proof height for IBC SovereignMessage

---

crates/relayer/relayer-components/src/chain/impls/forward/mod.rs
crates/relayer/relayer-components/src/chain/impls/forward/send_message.rs
crates/sovereign/sovereign-chain-components/src/sovereign/components.rs
crates/sovereign/sovereign-relayer/src/contexts/sovereign_chain.rs
crates/sovereign/sovereign-rollup-components/src/components.rs
crates/sovereign/sovereign-rollup-components/src/impls/mod.rs
crates/sovereign/sovereign-rollup-components/src/impls/send_message.rs

Add partial support for sending multiple messages to Sovereign rollup, by sequentially sending one message at a time.

Support sending multiple messages to Sovereign rollup

---

Cargo.toml
crates/relayer/relayer-components-extra/src/batch/worker.rs
crates/relayer/relayer-components-extra/src/build/components/relay/batch.rs
crates/relayer/relayer-components-extra/src/build/traits/cache.rs
crates/relayer/relayer-components-extra/src/components/extra/build.rs
crates/relayer/relayer-components/src/build/components/chain/cache.rs
crates/relayer/relayer-components/src/build/components/relay/cache.rs
crates/relayer/relayer-components/src/build/traits/cache.rs
crates/relayer/relayer-components/src/components/default/build.rs
crates/relayer/relayer-components/src/components/default/transaction.rs
crates/relayer/relayer-components/src/relay/impls/packet_lock.rs
crates/relayer/relayer-components/src/transaction/impls/allocate_nonce_with_mutex.rs
crates/relayer/relayer-components/src/transaction/traits/nonce/nonce_mutex.rs
crates/runtime/async-runtime-components/src/subscription/impls/stream.rs
crates/sovereign/sovereign-relayer/src/contexts/sovereign_rollup.rs

With the release of [Rust v1.79](https://blog.rust-lang.org/2024/06/13/Rust-1.79.0.html), it is now possible to use _associated type item bounds_, which would propagate the use of trait bounds in associated types, without requiring them to be added to the `where` clause on the use site.
This PR serves as a proof of concept that makes use of associated item bounds to simplify some of the use of `Runtime: HasMutex` in Hermes SDK.

Simplify some use of HasMutex bounds

---

CHANGELOG.md
crates/cosmos/cosmos-chain-components/src/components/cosmos_to_cosmos.rs
crates/cosmos/cosmos-chain-components/src/impls/client/create_client_message.rs
crates/cosmos/cosmos-chain-components/src/impls/client/update_client_message.rs
crates/cosmos/cosmos-chain-components/src/impls/types/create_client_options.rs
crates/cosmos/cosmos-chain-components/src/types/messages/client/update.rs
crates/cosmos/cosmos-chain-components/src/types/payloads/client.rs
crates/cosmos/cosmos-wasm-relayer/src/impls/update_client_message.rs
crates/relayer/relayer-components/src/chain/traits/types/timestamp.rs
crates/solomachine/solomachine-chain-components/src/impls/cosmos/update_client_message.rs

- Remove unused constraints in `HasTimestampType::Timestamp`.
- Update the `header` field in `CosmosUpdateClientMessage` to use `prost_types::Any` instead of `ibc_proto::Any`.
- Generalize the `CreateClientMessageBuilder` instance `BuildCosmosCreateClientMessage` to `BuildAnyCreateClientMessage`, and allows generic `CreateClientPayload` that has `client_state: Counterparty::ClientState` and `consensus_state: Counterparty::ConsensusState` fields.
- Rename the `ProvideCreateClientMessageOptionsType` instance in Cosmos from `ProvideCosmosCreateClientSettings` to `ProvideNoCreateClientMessageOptionsType`, with `CreateClientMessageOptions = ()`.

Minor refactoring

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/cosmos/cosmos-relayer/src/impls/error.rs
crates/cosmos/cosmos-test-components/src/chain/impls/proposal/poll_status.rs
crates/cosmos/cosmos-test-components/src/chain/impls/proposal/query_status.rs
crates/cosmos/cosmos-test-components/src/chain/types/proposal_status.rs
crates/test/test-components/src/chain/traits/proposal/poll_status.rs
crates/wasm/wasm-test-components/src/impls/bootstrap/build_chain_driver.rs
crates/wasm/wasm-test-components/src/impls/bootstrap/node_config.rs
flake.lock
nix/tendermint-wasm-client/wasm-rust-toolchain.toml

- Refactor `poll_proposal_status` to accept a list of wanted status.
- Make Cosmos implementation of `query_proposal_status` return error if the proposal failed.
- Introduce `ProposalFailed` error type that needs to be handled by `ErrorRaiser` implementation.

Improve error messages when submitting Wasm client proposals

---

CHANGELOG.md
crates/chain/chain-components/src/traits/message_builders/update_client.rs
crates/chain/chain-components/src/traits/payload_builders/create_client.rs
crates/chain/chain-components/src/traits/payload_builders/update_client.rs
crates/chain/chain-components/src/traits/types/create_client.rs
crates/chain/chain-components/src/traits/types/update_client.rs
crates/cosmos/cosmos-chain-components/src/components/client.rs
crates/cosmos/cosmos-chain-components/src/components/cosmos_to_cosmos.rs
crates/cosmos/cosmos-relayer/src/contexts/chain.rs
crates/cosmos/cosmos-wasm-relayer/src/components/cosmos_to_wasm_cosmos.rs
crates/cosmos/cosmos-wasm-relayer/src/context/chain.rs
crates/solomachine/solomachine-chain-components/src/components/cosmos.rs

- In `CosmosChainClientComponents`, delegate the following components to `UseDelegate<DelegateCosmosChainComponents>`:
`CreateClientPayloadTypeComponent`, `UpdateClientPayloadTypeComponent`,
`CreateClientPayloadOptionsTypeComponent`, `CreateClientPayloadBuilderComponent`,
`UpdateClientPayloadBuilderComponent`.
- To use CosmosChain with a concrete counterparty, the respective components need to be implemented in
`<DelegateCosmosChainComponents as DelegateComponent<Counterparty>>::Delegate`.

Delegate all create and update client types and methods based on counterparty

---

crates/chain/chain-components/src/impls/queries/consensus_state_height.rs
crates/chain/chain-components/src/impls/queries/consensus_state_heights.rs
crates/chain/chain-components/src/impls/queries/mod.rs
crates/chain/chain-components/src/traits/queries/consensus_state_height.rs
crates/cli/cli-components/src/impls/commands/queries/consensus_state.rs
crates/relayer/relayer-components-extra/src/components/extra/closures/chain/channel_handshake.rs
crates/relayer/relayer-components-extra/src/components/extra/closures/relay/ack_packet_relayer.rs
crates/relayer/relayer-components-extra/src/components/extra/closures/relay/message_sender.rs
crates/relayer/relayer-components/src/components/default/closures/relay/ack_packet_relayer.rs
crates/relayer/relayer-components/src/components/default/closures/relay/packet_relayer.rs

Add `QueryLatestConsensusStateHeightAsHeights` as a placeholder implementation for querying all consensus state heights using `ConsensusStateHeightsQuerier`, by returning only the latest client state height to be used as the trusted height. This can be used for partial chain implementations, where the query method for getting all consensus state heights is not available.
This would not work in the corner case when the relayer tries to perform UpdateClient with a target height that is lower than the latest height. In that case, if this is used together with `QueryConsensusStateHeightsAndFindHeightBefore`, then the error `NoConsensusStateAtLessThanHeight` would be returned. With retry logic, the relayer should be able to retry relaying the packet, and use an updated target height that …

Implement placeholder query of latest client state height as consensus state heights

---

crates/test/test-components/src/chain_driver/impls/wait.rs

It turns out that Osmosis can take anywhere between 5~10 seconds to fully start up a chain full node, even in a fresh local environment.

Increase wait timeout to allow Osmosis to start up

---

crates/cosmos/cosmos-relayer/src/contexts/relay.rs
crates/cosmos/cosmos-wasm-relayer/src/context/cosmos_to_wasm_cosmos_relay.rs
crates/cosmos/cosmos-wasm-relayer/src/context/wasm_cosmos_relay.rs
crates/relayer/relayer-components/src/components/default/relay.rs
crates/relayer/relayer-components/src/relay/impls/selector.rs

- Implement `ClientIdAtGetter` for `SelectRelayChains`, as missed in #498.
- Add `MaxErrorRetryGetterComponent` and `PacketLockComponent` to DefaultRelayPreset

Fix relay context selector

---

crates/chain/chain-components/src/traits/message_builders/channel_handshake.rs
crates/chain/chain-components/src/traits/message_builders/create_client.rs
crates/chain/chain-components/src/traits/payload_builders/channel_handshake.rs
crates/chain/chain-components/src/traits/queries/channel_end.rs
crates/chain/chain-components/src/traits/types/channel.rs
crates/chain/chain-components/src/traits/types/create_client.rs
crates/cosmos/cosmos-chain-components/src/components/client.rs
crates/cosmos/cosmos-chain-components/src/impls/channel/channel_handshake_message.rs
crates/cosmos/cosmos-chain-components/src/impls/connection/connection_handshake_message.rs
crates/cosmos/cosmos-chain-components/src/impls/queries/chain_status.rs
crates/cosmos/cosmos-chain-components/src/types/messages/channel/open_confirm.rs
crates/cosmos/cosmos-chain-components/src/types/messages/connection/open_ack.rs
crates/cosmos/cosmos-chain-components/src/types/messages/connection/open_confirm.rs
crates/cosmos/cosmos-chain-components/src/types/messages/connection/open_init.rs
crates/cosmos/cosmos-chain-components/src/types/messages/connection/open_try.rs
crates/cosmos/cosmos-relayer/src/contexts/chain.rs
crates/solomachine/solomachine-chain-components/src/impls/cosmos/channel_handshake_message.rs
crates/solomachine/solomachine-chain-components/src/impls/cosmos/connection_handshake_message.rs

Related: https://github.com/informalsystems/ibc-starknet/pull/149

Minor refactoring for channel handshake

---

crates/cosmos/cosmos-encoding-components/src/impls/chain_id.rs
crates/cosmos/cosmos-encoding-components/src/impls/mod.rs

This PR adds a component a `EncodeChainIdField` component used for encoding and decoding `ibc-rs` type `ChainId`
______

Add for ibc-rs `ChainId` encoding and decoding component

---

Cargo.lock
Cargo.toml
crates/cosmos/cosmos-relayer/src/contexts/birelay.rs
crates/cosmos/cosmos-relayer/src/contexts/build.rs
crates/cosmos/cosmos-relayer/src/contexts/chain.rs
crates/cosmos/cosmos-relayer/src/contexts/encoding.rs
crates/cosmos/cosmos-relayer/src/contexts/relay.rs

This is a short PR to simplify the definition of Cosmos contexts using the `#[cgp_context]` macro introduced in https://github.com/contextgeneric/cgp/pull/66.

Use `#[cgp_context]` to simplify delegation of providers to Cosmos context

---

crates/chain/chain-components/src/traits/queries/packet_commitment.rs
crates/cosmos/cosmos-chain-components/src/impls/queries/packet_commitment.rs

Needed for https://github.com/informalsystems/ibc-starknet/pull/297
______

refactor: allow to return `None` if packet commitment not found

---

crates/cli/cli/src/commands/query/channel/ends.rs
crates/cosmos/cosmos-chain-components/src/impls/queries/abci.rs
crates/cosmos/cosmos-chain-components/src/impls/queries/chain_id.rs
crates/cosmos/cosmos-chain-components/src/impls/queries/channel_end.rs
crates/cosmos/cosmos-chain-components/src/impls/queries/client_state.rs
crates/cosmos/cosmos-chain-components/src/impls/queries/connection_end.rs
crates/cosmos/cosmos-chain-components/src/impls/queries/consensus_state.rs
crates/cosmos/cosmos-chain-components/src/impls/queries/packet_acknowledgement.rs
crates/cosmos/cosmos-chain-components/src/impls/queries/packet_commitment.rs
crates/cosmos/cosmos-chain-components/src/impls/queries/packet_receipt.rs
crates/cosmos/cosmos-chain-components/src/impls/queries/received_ack.rs
crates/cosmos/cosmos-chain-components/src/impls/unbonding_period.rs
crates/cosmos/cosmos-chain-components/src/traits/abci_query.rs

Due to the quirks of Golang, the ABCI query actually returns empty bytes when a given path is not found in the Merkle store of a Cosmos chain. Currently, when an entry like client state is not found, the relayer would just fail with a confusing error message of failing to decode the empty bytes.
This PR fixes the issue by making the ABCI querier return an `Option<Vec<u8>>`, with `None` returned if empty bytes are returned from the full node.

Return `Option` in ABCI query

---

Cargo.lock
crates/chain/chain-components/src/impls/payload_builders/packet.rs
crates/chain/chain-components/src/traits/queries/packet_receipt.rs
crates/cosmos/cosmos-chain-components/src/impls/queries/packet_receipt.rs
crates/cosmos/cosmos-relayer/src/impls/error.rs
crates/relayer/relayer-components/src/relay/impls/auto_relayers/poll_event.rs
crates/test/test-components/Cargo.toml
crates/test/test-components/src/chain/impls/assert/poll_assert_eventual_amount.rs

Closes: #XXX
Following https://github.com/informalsystems/hermes-sdk/pull/544 this PR changes `query_packet_receipt` to return `Option<Chain::PacketReceipt>`.
This PR also adds logs for:
* Auto relaying
* Eventual balance assertion failure
______

Update `query_packet_receipt` to return `Option<Chain::PacketReceipt>`

---

crates/cosmos/cosmos-integration-tests/src/impls/bootstrap/build_cosmos_chain.rs

This PR increases the sleep time in `build_chain_with_node_config` to avoid `tcp connect error: Connection refused (os error 61)` error in tests
______

Increase sleep time in `build_chain_with_node_config`

---

Cargo.lock
crates/cosmos/cosmos-chain-components/Cargo.toml
crates/cosmos/cosmos-chain-components/src/impls/transaction/query_tx_response.rs

This PR attempts to fix a race condition issue when the relayer interacts with multiple full nodes through a public RPC endpoint.
Previously, when the relayer polls for a tx response, it immediately returns and continue relaying operations as soon as the tx response becomes available. Although this works in local settings or when the relayer has a dedicated full node, this approach may not work when the relayer interacts with multiple full nodes.
The main issue is that when the relayer found a tx response from one full node, the other full nodes may still be lagging behind the latest block, and thus not have the tx response available. If the relayer proceeds immediately and try to query for merkle proofs such as ack from other full nodes, then that proof may still not be available.
An …

Wait for chain to progress one height when a tx response just becomes available

---

crates/cosmos/cosmos-chain-components/src/traits/grpc_address.rs
crates/cosmos/cosmos-integration-tests/src/impls/bootstrap/build_cosmos_chain.rs
crates/test/test-suite/src/tests/clearing.rs

Instead of always waiting for the chain to reach height 5, we directly poll for the chain's GRPC service to become ready.
This polling is needed, as Osmosis' GRPC service starts much slower than other Cosmos chains.

Wait for Cosmos chain GRPC service to become ready in bootstrap

---

crates/cosmos/cosmos-integration-tests/tests/filter.rs
crates/cosmos/cosmos-relayer/src/contexts/chain.rs
crates/cosmos/cosmos-test-components/src/chain/impls/messages/ibc_transfer.rs
crates/cosmos/cosmos-test-components/src/chain/impls/transfer/amount.rs
crates/cosmos/cosmos-test-components/src/chain/impls/transfer/timeout.rs
crates/test/test-components/src/chain/impls/ibc_transfer.rs
crates/test/test-components/src/chain/traits/messages/ibc_transfer.rs
crates/test/test-components/src/chain/traits/transfer/amount.rs
crates/test/test-components/src/chain/traits/transfer/ibc_transfer.rs
crates/test/test-components/src/chain/traits/transfer/timeout.rs
crates/test/test-suite/src/tests/clearing.rs
crates/test/test-suite/src/tests/transfer.rs

- Allow `build_ibc_token_transfer_message` to return more than one messages.
- Add `PhantomData<Counterparty>` parameter to IBC transfer methods to help with type inference.
- Fix `build_ibc_token_transfer_message` to accept timeout from `Counterparty` instead of `Self`.
- Accept and additional `Counterparty::ChainStatus` parameter in `ibc_transfer_token` to derive timeout from it.

Refactoring and fix IBC transfer interfaces

---

crates/cosmos/cosmos-chain-preset/src/presets/chain.rs
crates/test/test-components/src/chain/impls/assert/assert_duration.rs
crates/test/test-components/src/chain/impls/assert/mod.rs
crates/test/test-components/src/chain/impls/assert/poll_assert_eventual_amount.rs

this is required for ibc-starknet as the e2e tests are failing at `ubuntu-arm` for packet timeout being not enough.

refactor: packet timeout and polling

---

crates/cosmos/cosmos-relayer/src/contexts/birelay.rs
docs/notes/README.md
docs/notes/context-fields.md
docs/notes/crate-organization.md
docs/notes/navigation.md

[Rendered](https://github.com/informalsystems/hermes-sdk/tree/soares/docs-3/docs/notes#hermes-sdk-architecture-notes)
Follow up on #596.
This PR adds new notes for [code navigation](https://github.com/informalsystems/hermes-sdk/blob/soares/docs-3/docs/notes/navigation.md) and [context fields](https://github.com/informalsystems/hermes-sdk/blob/soares/docs-3/docs/notes/context-fields.md).

Write Architecture Notes Documentation, part 3

---

crates/chain/chain-type-components/src/traits/types/event.rs
crates/relayer/relayer-components/src/relay/impls/auto_relayers/poll_event.rs
crates/relayer/relayer-components/src/transaction/traits/types/signer.rs
crates/relayer/relayer-components/src/transaction/traits/types/tx_response.rs

Closes: #XXX
This PR adds logic to retry the `query_block_events` at the same height if it fails after 1 second.
______

Retry querying events if query fails during event polling

---

Cargo.lock
crates/cosmos/cosmos-integration-tests/src/contexts/binary_channel/test_driver.rs
crates/cosmos/cosmos-test-components/Cargo.toml
crates/cosmos/cosmos-test-components/src/chain/impls/mod.rs
crates/cosmos/cosmos-test-components/src/chain/impls/recover_client.rs
crates/test/test-components/src/test_case/traits/mod.rs
crates/test/test-components/src/test_case/traits/recover_client.rs
crates/test/test-suite/src/tests/recover_client.rs
crates/test/test-suite/src/traits/types.rs

This PR improves the test driver by removing Cosmos dependencies required for client recovery test.
Previously we added components related to proposals, e.g. `CanQueryProposalStatus`, to the `CanUseBinaryTestDriverMethods` trait. But these are Cosmos specific.
Instead this PR adds a new component `RecoverClientHandlerComponent` which allows specific implementations, such as querying the proposal status and sending relevant messages for Cosmos <-> Cosmos.
______

Split dependencies for client recovery test

---

crates/cosmos/cosmos-integration-tests/src/contexts/binary_channel/test_driver.rs
crates/cosmos/cosmos-integration-tests/src/contexts/chain_driver.rs
crates/cosmos/cosmos-integration-tests/src/impls/fork.rs
crates/cosmos/cosmos-integration-tests/src/impls/mod.rs
crates/cosmos/cosmos-integration-tests/src/impls/node.rs
crates/relayer/relayer-components/src/relay/impls/event_relayers/packet_event.rs
crates/test/test-components/src/setup/traits/node.rs
crates/test/test-components/src/test_case/traits/mod.rs
crates/test/test-components/src/test_case/traits/node.rs
crates/test/test-suite/src/tests/misebehaviour.rs
crates/test/test-suite/src/traits/types.rs

Closes: #XXX
This PR Moves the Halting and resuming full node components from being a test driver component to a chain driver component
______

fix: move Halt and resume full nodes to be ChainDriver components
